// Generated by gradle, in app/build.gradle.
#include <stdio.h>
#include <stdlib.h>

const char* QCI_BUILD_ID = "999";
const char* QCI_JOB_ID = "999";
const char* QCI_BUILD_NUMBER = "999";

extern "C" char SO_FILE_VERSION[]  __attribute__ ((section (".bugly_version"))) = "999.999.999";
